name: Ubuntu Cinnamon Remix 21.10 Impish (development branch) Daily

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: ' 0 14 * * * '

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: debian:buster
      options: --privileged -it

    steps:
    - uses: actions/checkout@v2

    - name: Install debootstrap/git
      run: apt update && apt install git debootstrap -y

    - name: Build ISO
      run: |
        cd /
        git clone https://github.com/Ubuntu-Cinnamon-Remix/iso-builder
        cd iso-builder
        ./build.sh etc/terraform.conf

    - uses: actions/upload-artifact@v2
      with:
        name: Ubuntu Cinnamon Remix 21.10 Impish (development branch) Daily
        path: /iso-builder/builds/
